seed: 42

data:
  # Chemin absolu vers le dossier des images
  img_dir: "/kaggle/input/datasets/adityajn105/flickr30k/Images"
  
  # Chemin exact que tu as trouvé avec la commande find
  captions_file: "/kaggle/input/datasets/adityajn105/flickr30k/captions.txt"
  
  # Tes fichiers de split dans l'espace de travail (assure-toi qu'ils existent)
  train_file: "/kaggle/working/data/Flickr30k/trainImages.txt"
  dev_file: "/kaggle/working/data/Flickr30k/devImages.txt"
  test_file: "/kaggle/working/data/Flickr30k/testImages.txt"

output:
  model_dir: "/kaggle/working/outputs"

model:
  embed_size: 128
  hidden_size: 256
  num_layers: 1
  dropout: 0.3

training:
  batch_size: 16
  num_epochs: 20
  learning_rate: 0.0001
  freq_threshold: 10

output:
  model_dir: "outputs"