seed: 42

data:
  img_dir: "data/Flicker8k_Dataset"
  captions_file: "data/Flickr8k.token.txt"
  train_file: "data/Flickr_8k.trainImages.txt"
  test_file: "data/Flickr_8k.testImages.txt"

model:
  embed_size: 512
  hidden_size: 1024
  num_layers: 2
  dropout: 0.5

training:
  batch_size: 64
  num_epochs: 30
  learning_rate: 0.001
  freq_threshold: 5

output:
  model_dir: "/content/drive/MyDrive/image-captioning-outputs/"